# EduTech Solutions - AI & ML Internship
## Task 1: Understanding Dataset & Data Types
**Tools:** Python (Pandas, NumPy)  
**Dataset:** Students Academic Performance

---

## Step 1: Import Libraries

In [ ]:
!pip install pandas
!pip install numpy

In [7]:
import sys
!{sys.executable} -m pip install pandas numpy
import pandas as pd
import numpy as np
print("Libraries imported!")
print(f"Pandas: {pd.__version__}, NumPy: {np.__version__}")

Collecting pandas
  Downloading pandas-3.0.3-cp314-cp314-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy in c:\users\user\appdata\local\programs\python\python314\lib\site-packages (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\user\appdata\roaming\python\python314\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Using cached tzdata-2026.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\user\appdata\roaming\python\python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.3-cp314-cp314-win_amd64.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ------------------------------------- -- 9.2/9.9 MB 51.6 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 30.8 MB/s  0:00:00
Using cached tzdata-2026.2-py2.py3-none-any.whl (349 kB)
Installing collected packages: tzdata, pandas

   ---------------------------------------- 0/2 [tzdata]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   ---------------------------------------- 2/2 [pandas]

Successfully installed pandas-3.0.3 tzdata-2026.2

[notice] A new release of pip is available: 25.2 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Libraries imported!
Pandas: 3.0.3, NumPy: 2.4.4

## Step 2: Load the Dataset
We use pd.read_csv() to load the CSV into a Pandas DataFrame.

In [8]:
df = pd.read_csv("students_academic_performance.csv")
print("Dataset loaded successfully!")
df.head()

Dataset loaded successfully!

,StudentID,Name,Age,Gender,Department,Year,AttendancePercent,MathScore,ScienceScore,EnglishScore,CGPA,ScholarshipHolder,PartTimeJob,Grade,City
0,1001,Student_1,23,Male,Biology,2,76.0,80.0,88,79,9.65,No,No,B,Bangalore
1,1002,Student_2,20,Female,Chemistry,4,88.6,68.0,43,91,NaN,No,No,A,Hyderabad
2,1003,Student_3,21,Male,Physics,3,NaN,80.0,38,46,7.21,No,Yes,B,Mumbai
3,1004,Student_4,23,Female,Chemistry,3,92.6,99.0,69,32,9.30,No,No,C,Bangalore
4,1005,Student_5,19,Female,Biology,1,77.6,35.0,95,61,4.50,No,Yes,C,Delhi

## Step 3: Shape & Dimensions
.shape returns (rows, columns)

In [9]:
print(f"Shape: {df.shape}")
print(f"Rows: {df.shape[0]}")
print(f"Columns: {df.shape[1]}")
print(f"Total Cells: {df.size}")
print(f"Column Names: {list(df.columns)}")

Shape: (200, 15)
Rows: 200
Columns: 15
Total Cells: 3000
Column Names: ['StudentID', 'Name', 'Age', 'Gender', 'Department', 'Year', 'AttendancePercent', 'MathScore', 'ScienceScore', 'EnglishScore', 'CGPA', 'ScholarshipHolder', 'PartTimeJob', 'Grade', 'City']

## Step 4: Data Structure with .info()
Shows column names, non-null counts, data types, and memory usage.

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   StudentID          200 non-null    int64
 1   Name               200 non-null    str
 2   Age                200 non-null    int64
 3   Gender             200 non-null    str
 4   Department         200 non-null    str
 5   Year               200 non-null    int64
 6   AttendancePercent  185 non-null    float64
 7   MathScore          190 non-null    float64
 8   ScienceScore       200 non-null    int64
 9   EnglishScore       200 non-null    int64
 10  CGPA               192 non-null    float64
 11  ScholarshipHolder  200 non-null    str
 12  PartTimeJob        200 non-null    str
 13  Grade              200 non-null    str
 14  City               195 non-null    str
dtypes: float64(3), int64(5), str(7)
memory usage: 23.6 KB

## Step 5: Document Data Types
- int64: whole numbers
- float64: decimal numbers
- object: text/strings

In [11]:
dtype_summary = pd.DataFrame({
    "Column": df.columns,
    "Data Type": df.dtypes.values,
    "Non-Null Count": df.count().values,
    "Null Count": df.isnull().sum().values
})
print(dtype_summary.to_string(index=False))

           Column Data Type  Non-Null Count  Null Count
        StudentID     int64             200           0
             Name       str             200           0
              Age     int64             200           0
           Gender       str             200           0
       Department       str             200           0
             Year     int64             200           0
AttendancePercent   float64             185          15
        MathScore   float64             190          10
     ScienceScore     int64             200           0
     EnglishScore     int64             200           0
             CGPA   float64             192           8
ScholarshipHolder       str             200           0
      PartTimeJob       str             200           0
            Grade       str             200           0
             City       str             195           5

## Step 6: Statistical Summary with .describe()
Provides count, mean, std, min, max, and quartiles for numerical columns.

In [12]:
print("=== NUMERICAL COLUMNS ===")
df.describe().round(2)

=== NUMERICAL COLUMNS ===

,StudentID,Age,Year,AttendancePercent,MathScore,ScienceScore,EnglishScore,CGPA
count,200.00,200.00,200.00,185.00,190.00,200.00,200.00,192.00
mean,1100.50,20.56,2.35,73.04,63.72,64.44,64.22,7.03
std,57.88,2.28,1.16,14.04,19.97,19.57,19.85,1.65
min,1001.00,17.00,1.00,50.70,30.00,30.00,30.00,4.05
25%,1050.75,19.00,1.00,59.60,48.00,46.75,46.75,5.77
50%,1100.50,20.00,2.00,71.90,64.00,65.50,62.50,7.20
75%,1150.25,23.00,3.00,84.50,80.00,83.00,81.25,8.26
max,1200.00,24.00,4.00,99.50,99.00,99.00,99.00,9.96

In [13]:
print("=== CATEGORICAL COLUMNS ===")
df.describe(include=["object"])

=== CATEGORICAL COLUMNS ===

C:\Users\user\AppData\Local\Temp\ipykernel_19296\1119241197.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include=["object"])

,Name,Gender,Department,ScholarshipHolder,PartTimeJob,Grade,City
count,200,200,200,200,200,200,195
unique,200,3,5,2,2,5,6
top,Student_1,Female,Biology,No,No,B,Delhi
freq,1,105,50,144,113,61,42

## Step 7: Numerical vs Categorical Variables

| Type | Definition | Examples |
|------|------------|----------|
| Numerical - Continuous | Any value in a range | CGPA, AttendancePercent |
| Numerical - Discrete | Countable whole values | Age, Year, Scores |
| Categorical - Nominal | No natural order | Gender, City, Department |
| Categorical - Ordinal | Has natural order | Grade (A>B>C>D>F) |

In [15]:
numerical_cols = df.select_dtypes(include=["int64", "float64"]).columns.tolist()
categorical_cols = df.select_dtypes(include=["object"]).columns.tolist()

print(f"NUMERICAL Columns ({len(numerical_cols)}):")
for col in numerical_cols:
    kind = "Discrete" if df[col].nunique() <= 15 else "Continuous"
    print(f"  {col:<22} -> {kind} (unique: {df[col].nunique()})")

print("")
print(f"CATEGORICAL Columns ({len(categorical_cols)}):")
for col in categorical_cols:
    print(f"  {col:<22} -> (unique: {df[col].nunique()})")

NUMERICAL Columns (8):
  StudentID              -> Continuous (unique: 200)
  Age                    -> Discrete (unique: 8)
  Year                   -> Discrete (unique: 4)
  AttendancePercent      -> Continuous (unique: 162)
  MathScore              -> Continuous (unique: 68)
  ScienceScore           -> Continuous (unique: 67)
  EnglishScore           -> Continuous (unique: 66)
  CGPA                   -> Continuous (unique: 168)

CATEGORICAL Columns (7):
  Name                   -> (unique: 200)
  Gender                 -> (unique: 3)
  Department             -> (unique: 5)
  ScholarshipHolder      -> (unique: 2)
  PartTimeJob            -> (unique: 2)
  Grade                  -> (unique: 5)
  City                   -> (unique: 6)

C:\Users\user\AppData\Local\Temp\ipykernel_19296\2048318508.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(include=["object"]).columns.tolist()

## Step 8: Missing Values Analysis
Missing values must be identified before any ML work.

In [17]:
missing_count = df.isnull().sum()
missing_pct = (missing_count / len(df) * 100).round(2)
missing_report = pd.DataFrame({"Missing Count": missing_count, "Missing %": missing_pct})
missing_report = missing_report[missing_report["Missing Count"] > 0].sort_values("Missing Count", ascending=False)

print("Missing Values Report:")
print(missing_report.to_string())
print(f"Total missing: {missing_count.sum()} cells")

Missing Values Report:
                   Missing Count  Missing %
AttendancePercent             15        7.5
MathScore                     10        5.0
CGPA                           8        4.0
City                           5        2.5
Total missing: 38 cells

## Step 9: Unique Values in Categorical Columns

In [19]:
for col in categorical_cols:
    if col != "Name":
        vc = df[col].value_counts()
        print(f"Column: {col} | Unique: {df[col].nunique()}")
        print(f"Values: {list(df[col].dropna().unique())}")
        print(vc.to_string())
        print("")

Column: Gender | Unique: 3
Values: ['Male', 'Female', 'Other']
Gender
Female    105
Male       88
Other       7

Column: Department | Unique: 5
Values: ['Biology', 'Chemistry', 'Physics', 'Mathematics', 'Computer Science']
Department
Biology             50
Mathematics         42
Chemistry           39
Computer Science    39
Physics             30

Column: ScholarshipHolder | Unique: 2
Values: ['No', 'Yes']
ScholarshipHolder
No     144
Yes     56

Column: PartTimeJob | Unique: 2
Values: ['No', 'Yes']
PartTimeJob
No     113
Yes     87

Column: Grade | Unique: 5
Values: ['B', 'A', 'C', 'D', 'F']
Grade
B    61
C    61
A    54
D    15
F     9

Column: City | Unique: 6
Values: ['Bangalore', 'Hyderabad', 'Mumbai', 'Delhi', 'Pune', 'Chennai']
City
Delhi        42
Bangalore    41
Pune         34
Hyderabad    29
Mumbai       25
Chennai      24

## Step 10: Final Summary Report

In [20]:
print("=" * 55)
print("TASK 1 - FINAL SUMMARY REPORT")
print("=" * 55)
print(f"Dataset: Students Academic Performance")
print(f"Records: {df.shape[0]} | Features: {df.shape[1]}")
print("")
print("Data Types:")
print(f"  int64   : {list(df.select_dtypes(include=['int64']).columns)}")
print(f"  float64 : {list(df.select_dtypes(include=['float64']).columns)}")
print(f"  object  : {list(df.select_dtypes(include=['object']).columns)}")
print("")
print(f"Missing Values: {df.isnull().sum().sum()} cells total")
print("")
print("Key Insights:")
print("  1. CGPA & AttendancePercent are Continuous (float)")
print("  2. Age, Year, Scores are Discrete (int)")
print("  3. Grade (A/B/C/D/F) is Ordinal Categorical")
print("  4. Gender, Department, City are Nominal Categorical")
print("  5. ScholarshipHolder is Binary Categorical (Yes/No)")
print("=" * 55)
print("Task 1 Complete!")

=======================================================
TASK 1 - FINAL SUMMARY REPORT
=======================================================
Dataset: Students Academic Performance
Records: 200 | Features: 15

Data Types:
  int64   : ['StudentID', 'Age', 'Year', 'ScienceScore', 'EnglishScore']
  float64 : ['AttendancePercent', 'MathScore', 'CGPA']
  object  : ['Name', 'Gender', 'Department', 'ScholarshipHolder', 'PartTimeJob', 'Grade', 'City']

Missing Values: 38 cells total

Key Insights:
  1. CGPA & AttendancePercent are Continuous (float)
  2. Age, Year, Scores are Discrete (int)
  3. Grade (A/B/C/D/F) is Ordinal Categorical
  4. Gender, Department, City are Nominal Categorical
  5. ScholarshipHolder is Binary Categorical (Yes/No)
=======================================================
Task 1 Complete!

C:\Users\user\AppData\Local\Temp\ipykernel_19296\1849950368.py:10: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  print(f"  object  : {list(df.select_dtypes(include=['object']).columns)}")

## Interview Questions & Answers

**Q1: Structured vs Unstructured data?**  
- Structured: organized in rows/columns (CSV, SQL tables) - like our student dataset  
- Unstructured: no fixed format (text, images, audio) - like student feedback essays

**Q2: Numerical vs Categorical?**  
- Numerical: measurable quantities - Age (22), CGPA (8.5), Score (75)  
- Categorical: labels/groups - Gender ("Male"), Grade ("A"), Department ("CS")

**Q3: Continuous vs Discrete?**  
- Continuous: infinite values in a range - CGPA (7.23...), AttendancePercent  
- Discrete: countable whole values - Year (1,2,3,4), Age (17,18...24)

**Q4: Handling missing values?**


**Q5: What does .describe() tell you?**  
Provides count, mean, std deviation, min, max, and quartiles (25%, 50%, 75%) for each numerical column. Helps understand data distribution and detect outliers.